# Generated by Django 5.2.5 on 2026-01-25 02:01

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=10, max_length=13, null=True, prefix='INV'),
        ),
    ]
