# Generated by Django 5.2.5 on 2026-01-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash On Delivery'), ('KHALTI', 'Khalti'), ('ESEWA', 'eSewa'), ('PAYPAL', 'paypal')], max_length=20, null=True),
        ),
    ]
