# Generated by Django 5.2.5 on 2026-01-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_payer_id_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_already',
            field=models.BooleanField(default=False),
        ),
    ]
