# Generated by Django 5.2.5 on 2026-01-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_is_already'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_already',
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
