# Generated by Django 5.2.5 on 2026-01-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
