# Generated by Django 5.2.5 on 2026-01-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_num',
        ),
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
