# Generated by Django 5.2.5 on 2026-01-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0013_remove_address_profile_address_profile'),
        ('main', '0009_remove_order_order_num_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='e_auth.address'),
        ),
    ]
