# Generated by Django 5.2.5 on 2026-02-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_price',
        ),
    ]
