# Generated by Django 6.0 on 2026-01-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
