# Generated by Django 5.2.5 on 2026-01-27 06:50

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_auth', '0002_remove_profile_user_delete_buyer_delete_profile'),
        ('main', '0006_remove_order_is_already_order_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghij12345', length=10, max_length=20, prefix='pro', unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='static/css/icon.jpeg', max_length=255, null=True, verbose_name='profile_image')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image')),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_costomer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('home', models.BooleanField(blank=True, default=True, null=True)),
                ('office', models.BooleanField(blank=True, default=False, null=True)),
                ('temporary', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ManyToManyField(related_name='user_address', to='e_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, null=True)),
                ('pan', models.CharField(max_length=50, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=50)),
                ('chat_resp_time', models.PositiveIntegerField(default='100', validators=[django.core.validators.MaxValueValidator(100)])),
                ('shipping_on_time', models.PositiveIntegerField(default='100', validators=[django.core.validators.MaxValueValidator(100)])),
                ('authentic_rating', models.PositiveIntegerField(default='100', validators=[django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='e_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_products', models.ManyToManyField(blank=True, related_name='bought', to='main.product')),
                ('shipping', models.ForeignKey(default='standard', on_delete=django.db.models.deletion.CASCADE, to='main.shippingoption')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='e_auth.profile')),
                ('following_sellers', models.ManyToManyField(blank=True, related_name='following', to='e_auth.vendor')),
            ],
        ),
    ]
