# Generated by Django 5.2.5 on 2026-01-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0003_initial'),
        ('main', '0006_remove_order_is_already_order_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_costomer',
            new_name='is_customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_products', models.ManyToManyField(blank=True, related_name='bought', to='main.product')),
                ('following_sellers', models.ManyToManyField(blank=True, related_name='following', to='e_auth.vendor')),
                ('shipping', models.ForeignKey(default='standard', on_delete=django.db.models.deletion.CASCADE, to='main.shippingoption')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='e_auth.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Costomer',
        ),
    ]
