# Generated by Django 5.2.5 on 2026-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0005_address_is_default_customer_total_spent'),
        ('main', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist_products',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='main.wishlist'),
        ),
    ]
