# Generated by Django 5.2.5 on 2026-01-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0006_customer_wishlist_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='user',
            new_name='profile',
        ),
    ]
