# Generated by Django 5.2.5 on 2026-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0007_rename_user_address_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bought_products',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wishlist_products',
        ),
        migrations.AddField(
            model_name='customer',
            name='bought_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist_products',
            field=models.IntegerField(default=0),
        ),
    ]
