# Generated by Django 5.2.5 on 2026-01-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0008_remove_customer_bought_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bought_products',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='wishlist_products',
            new_name='wishlists',
        ),
    ]
