# Generated by Django 5.2.5 on 2026-01-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0009_rename_bought_products_customer_orders_and_more'),
        ('main', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shippingoption'),
        ),
    ]
