# Generated by Django 5.2.5 on 2026-01-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0010_alter_customer_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
