# Generated by Django 5.2.5 on 2026-01-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0011_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='home',
        ),
        migrations.RemoveField(
            model_name='address',
            name='office',
        ),
        migrations.RemoveField(
            model_name='address',
            name='temporary',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('temporary', 'Temporary')], max_length=50, null=True),
        ),
    ]
