# Generated by Django 5.2.5 on 2026-01-29 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0012_remove_address_home_remove_address_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='e_auth.profile'),
        ),
    ]
